# Generated by Django 4.2.11 on 2024-07-04 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batches",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
        migrations.AlterField(
            model_name="batches",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
        migrations.AlterField(
            model_name="mappersdata",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
        migrations.AlterField(
            model_name="mappersdata",
            name="GMTCreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620)
            ),
        ),
        migrations.AlterField(
            model_name="mappersdata",
            name="GMTModifiedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620)
            ),
        ),
        migrations.AlterField(
            model_name="mappersdata",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplates",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplates",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 21, 581620), null=True
            ),
        ),
    ]
