# Generated by Django 4.2.11 on 2024-07-04 07:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feeds",
            fields=[
                (
                    "CreatedDate",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 4, 0, 13, 24, 571690),
                        null=True,
                    ),
                ),
                (
                    "UpdatedDate",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 4, 0, 13, 24, 571690),
                        null=True,
                    ),
                ),
                ("Active", models.BooleanField(default=True)),
                ("FeedID", models.BigAutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "CreatedID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UpdatedID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedCategory",
            fields=[
                (
                    "CreatedDate",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 4, 0, 13, 24, 571690),
                        null=True,
                    ),
                ),
                (
                    "UpdatedDate",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 7, 4, 0, 13, 24, 571690),
                        null=True,
                    ),
                ),
                ("Active", models.BooleanField(default=True)),
                (
                    "FeedCategoryID",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "CreatedID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "UpdatedID",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
