# Generated by Django 4.2.11 on 2024-07-04 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedcategory",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 35, 856201), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedcategory",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 35, 856201), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feeds",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 35, 856201), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feeds",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 0, 14, 35, 856201), null=True
            ),
        ),
    ]
