# Generated by Django 4.2.11 on 2024-07-05 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_alter_feedcategory_createddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedcategory",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 21, 33, 56, 710552), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feedcategory",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 21, 33, 56, 710552), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feeds",
            name="CreatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 21, 33, 56, 710552), null=True
            ),
        ),
        migrations.AlterField(
            model_name="feeds",
            name="UpdatedDate",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 7, 4, 21, 33, 56, 710552), null=True
            ),
        ),
    ]
